export const CANDIDATE_DETAILS_SCHEMA = {
  name: "",
  grade: "",
  age: "",
  gender: "",
  contactNumber: "",
  nvsBranch: "",
  typesOfDisabilities: [],
  disabilityPercentage: "",
  eligibilityCriteria: [],
  medicalCondition: "",
  medicalOrSurgicalHistory: "",
  currentTreatmentAndMedication: "",
  sportingHistory: "",
  choiceOfSport: [],
  assistiveDevice: "",
  height: "",
  weight: "",
  backScratchTest: "",
  sitAndReach: "",
  chestThrow: "",
  plankTest: "",
  broadJump: "",
  pushUp: "",
  balanceLeft: "",
  balanceRight: "",
  sprint: "",
};
